image: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      CMAKE_ARGS: -G "Visual Studio 15 2017 Win64"

    - platform: x86
      CMAKE_ARGS: -G "Visual Studio 15 2017"

build_script:
  - mkdir build
  - cd build
  - cmake %CMAKE_ARGS% ..
  - cmake --build . --config Release

test_script:
  - ctest
